# Generated by Django 5.2 on 2026-02-16 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('type', models.CharField(choices=[('article', 'Article'), ('blog', 'Blog'), ('news', 'News'), ('event', 'Event')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business_AOP_Slab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=20)),
                ('income_min', models.BigIntegerField()),
                ('income_max', models.BigIntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('base_income', models.BigIntegerField()),
                ('base_tax', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('additional_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Business_AOP_Slab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=20)),
                ('income_min', models.BigIntegerField()),
                ('income_max', models.BigIntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('base_income', models.BigIntegerField()),
                ('base_tax', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('category', models.CharField(help_text='e.g. Basic Income Tax, Withholding Tax', max_length=100)),
                ('explanation', models.TextField(blank=True)),
                ('section_ref', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SuperTax4CRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField()),
                ('income_from', models.BigIntegerField()),
                ('income_to', models.BigIntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=20)),
                ('income_min', models.BigIntegerField()),
                ('income_max', models.BigIntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('base_income', models.BigIntegerField()),
                ('base_tax', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TaxBuddyApp.blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='TaxBuddyApp.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
