# Generated by Django 5.0.7 on 2025-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
