# Generated by Django 5.2 on 2026-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0002_faq_testimonial_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithholdingTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('property', 'Property Sale / Purchase'), ('banking', 'Banking & Finance'), ('salary', 'Salary & Employment'), ('business', 'Business / Contracts'), ('advance', 'Advance Tax'), ('other', 'Other Payments')], max_length=50)),
                ('section', models.CharField(help_text='e.g. Section 153(1)(b)', max_length=100)),
                ('description', models.CharField(help_text='e.g. Payments for services', max_length=300)),
                ('filer_rate', models.CharField(help_text='e.g. 8% or PKR 10,000', max_length=50)),
                ('non_filer_rate', models.CharField(blank=True, help_text='e.g. 16%', max_length=50)),
                ('who_deducts', models.CharField(blank=True, help_text='e.g. Prescribed persons', max_length=200)),
                ('threshold', models.CharField(blank=True, help_text='e.g. Above PKR 50,000', max_length=200)),
                ('tax_year', models.CharField(default='2025-2026', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Withholding Tax Rate',
                'verbose_name_plural': 'Withholding Tax Rates',
                'ordering': ['category', 'order', 'section'],
            },
        ),
    ]
