# Generated by Django 5.0.7 on 2026-05-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0003_withholdingtaxrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'order'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='page',
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('filer', 'Filer Status'), ('property', 'Property Tax'), ('salary', 'Salary Tax'), ('banking', 'Banking & Investments'), ('sales', 'Sales Tax'), ('general', 'General')], default='general', help_text='Used for filtering on homepage', max_length=20),
        ),
        migrations.AddField(
            model_name='withholdingtaxrate',
            name='late_filer_rate',
            field=models.CharField(blank=True, help_text='e.g. 7.5%', max_length=50),
        ),
        migrations.AlterField(
            model_name='withholdingtaxrate',
            name='filer_rate',
            field=models.CharField(help_text='e.g. 4.5% or PKR 10,000', max_length=50),
        ),
        migrations.AlterField(
            model_name='withholdingtaxrate',
            name='non_filer_rate',
            field=models.CharField(blank=True, help_text='e.g. 11.5%', max_length=50),
        ),
    ]
