# Generated by Django 5.2 on 2026-02-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0004_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
