# Generated by Django 5.0.7 on 2026-05-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0004_alter_faq_options_remove_faq_page_faq_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('category', models.CharField(choices=[('income_tax', 'Income Tax'), ('sales_tax', 'Sales Tax')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('related_blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TaxBuddyApp.blog')),
            ],
        ),
    ]
