# Generated by Django 5.0.7 on 2026-05-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0005_taxguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATLRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntn', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('business_name', models.CharField(blank=True, max_length=300)),
                ('tax_year', models.CharField(default='2025', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ATL Record',
                'ordering': ['ntn'],
                'indexes': [models.Index(fields=['ntn'], name='TaxBuddyApp_ntn_6293d7_idx')],
            },
        ),
    ]
