# Generated by Django 5.2 on 2026-05-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0006_atlrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='WHTRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Unique slug e.g. 236C_upto50m', max_length=40, unique=True)),
                ('section', models.CharField(help_text='ITO section e.g. 236C, 153(1)(b)', max_length=30)),
                ('cat', models.CharField(choices=[('property', 'Property'), ('banking', 'Banking & Finance'), ('dividends', 'Dividends'), ('imports', 'Imports'), ('goods', 'Goods / Supplies'), ('services', 'Services'), ('contracts', 'Contracts'), ('exports', 'Exports'), ('rent', 'Rent'), ('prizes', 'Prizes & Winnings'), ('vehicles', 'Vehicles'), ('salary', 'Salary'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('sub', models.CharField(blank=True, max_length=400)),
                ('rate_kind', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('slab', 'Slab-Based'), ('per_unit', 'Per Unit')], default='percentage', max_length=12)),
                ('filer', models.DecimalField(decimal_places=4, help_text='ATL / Filer rate (% or Rs.)', max_digits=12)),
                ('late_filer', models.DecimalField(decimal_places=4, help_text='Late Filer rate (% or Rs.)', max_digits=12)),
                ('non_filer', models.DecimalField(decimal_places=4, help_text='Non-ATL rate (% or Rs.)', max_digits=12)),
                ('nature', models.CharField(choices=[('WHT', 'Withholding Tax'), ('Advance Tax', 'Advance Tax')], max_length=20)),
                ('tax_type', models.CharField(choices=[('Final Tax', 'Final Tax'), ('Adjustable', 'Adjustable'), ('Minimum Tax', 'Minimum Tax'), ('Separate Block', 'Separate Block'), ('Fixed Amount', 'Fixed Amount')], db_column='type', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('tax_year', models.CharField(db_index=True, default='2025-26', max_length=10)),
                ('schedule_ref', models.CharField(blank=True, help_text='FBR Schedule reference', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'wht_rates',
                'ordering': ['sort_order', 'section', 'uid'],
                'indexes': [models.Index(fields=['tax_year', 'cat'], name='wht_rates_tax_yea_3357ee_idx'), models.Index(fields=['section'], name='wht_rates_section_998f70_idx')],
            },
        ),
    ]
