# Generated by Django 5.0.7 on 2025-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0006_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
