# Generated by Django 5.2 on 2026-07-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0007_whtrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200, unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('results_found', models.PositiveIntegerField(default=0)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-count'],
            },
        ),
        migrations.AddField(
            model_name='whtrate',
            name='base_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed tax before applying rate e.g. 6000', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='whtrate',
            name='slab_max',
            field=models.BigIntegerField(blank=True, help_text='Upper bound of slab, NULL = no limit', null=True),
        ),
        migrations.AddField(
            model_name='whtrate',
            name='slab_min',
            field=models.BigIntegerField(blank=True, help_text='Lower bound of slab e.g. 600001', null=True),
        ),
    ]
