# Generated by Django 5.2 on 2026-06-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0007_whtrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='whtrate',
            name='base_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed tax before applying rate e.g. 6000', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='whtrate',
            name='slab_max',
            field=models.BigIntegerField(blank=True, help_text='Upper bound of slab, NULL = no limit', null=True),
        ),
        migrations.AddField(
            model_name='whtrate',
            name='slab_min',
            field=models.BigIntegerField(blank=True, help_text='Lower bound of slab e.g. 600001', null=True),
        ),
    ]
