# Generated by Django 5.2 on 2026-07-19 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0008_searchquery_whtrate_base_tax_whtrate_slab_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='sro_page', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(choices=[('sro', 'SRO'), ('circular', 'Circular'), ('notification', 'Notification')], db_index=True, default='sro', max_length=20)),
                ('number', models.CharField(help_text='e.g. SRO 350(I)/2024 or Circular No. 3 of 2025', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('statute', models.CharField(choices=[('income_tax', 'Income Tax'), ('sales_tax', 'Sales Tax'), ('fed', 'Federal Excise'), ('customs', 'Customs')], db_index=True, max_length=20)),
                ('issue_date', models.DateField(db_index=True)),
                ('effective_date', models.DateField(blank=True, help_text='Blank = same as issue date', null=True)),
                ('subject', models.CharField(help_text='One-line: what this instrument is about', max_length=300)),
                ('summary', models.TextField(help_text='Plain-English: what changed, in simple words (150-300 words)')),
                ('who_affected', models.TextField(blank=True, help_text='Who does this apply to — e.g. property buyers, exporters, retailers')),
                ('old_rule', models.TextField(blank=True, help_text='Position BEFORE this instrument')),
                ('new_rule', models.TextField(blank=True, help_text='Position AFTER this instrument')),
                ('related_sections', models.CharField(blank=True, help_text='Comma-separated: 236C, 236K, 7E', max_length=300)),
                ('pdf', models.FileField(blank=True, help_text='Official PDF (recommended — FBR links break)', null=True, upload_to='instruments/')),
                ('fbr_link', models.URLField(blank=True, help_text='Official FBR page (optional backup)')),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_blog', models.ForeignKey(blank=True, help_text='Detailed analysis article (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='TaxBuddyApp.blog')),
            ],
            options={
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['instrument_type', 'statute', '-issue_date'], name='TaxBuddyApp_instrum_b1a36f_idx')],
            },
        ),
    ]
