# Generated by Django 5.2 on 2025-08-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=20)),
                ('income_min', models.BigIntegerField()),
                ('income_max', models.BigIntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_income', models.BigIntegerField()),
                ('base_tax', models.BigIntegerField()),
            ],
        ),
    ]
