# Generated by Django 5.2 on 2025-08-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0009_taxbracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxbracket',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
