# Generated by Django 5.2 on 2026-07-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0009_subscriber_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='e.g. Minimum Tax, ATL, Further Tax', max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_meaning', models.CharField(help_text='1-2 line simple definition — yahi AI engines quote karte hain', max_length=300)),
                ('explanation', models.TextField(help_text='Detailed simple-English explanation (100-250 words)')),
                ('legal_definition', models.TextField(blank=True, help_text='Statute ki exact/paraphrased definition (optional)')),
                ('section_ref', models.CharField(blank=True, help_text='e.g. Section 113, Income Tax Ordinance 2001', max_length=150)),
                ('example', models.TextField(blank=True, help_text='Practical example with Rs figures')),
                ('related_terms', models.CharField(blank=True, help_text='Comma-separated terms: FTR, Withholding Tax', max_length=300)),
                ('related_url', models.CharField(blank=True, help_text='Related calculator/guide path e.g. /SalaryCalculator/', max_length=200)),
                ('related_url_label', models.CharField(blank=True, help_text='Button text e.g. Try the Salary Calculator', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossary_terms', to='TaxBuddyApp.blog')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
    ]
