# Generated by Django 6.0.7 on 2026-08-10 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0010_glossaryterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFMVRateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text='e.g. Karachi 2024-25 (SRO 1724)', max_length=120, unique=True)),
                ('city', models.CharField(db_index=True, default='Karachi', max_length=60)),
                ('notification_number', models.CharField(help_text='e.g. S.R.O. 1724(I)/2024', max_length=120)),
                ('amendment_number', models.CharField(blank=True, help_text='e.g. S.R.O. 144(I)/2025', max_length=120)),
                ('notification_date', models.DateField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Blank = still in force', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('draft', 'Draft')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FMV Rate Version',
                'db_table': 'fmv_rate_versions',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFMVRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(help_text='SRO clause e.g. m, n, o, p, q, r, c, k, f', max_length=10)),
                ('property_type', models.CharField(choices=[('residential_open', 'Residential Open Plot'), ('residential_builtup', 'Residential Built-up'), ('flat', 'Flat / Apartment'), ('commercial_open', 'Commercial Open Plot'), ('commercial_builtup', 'Commercial Built-up'), ('industrial_open', 'Industrial Open Plot'), ('industrial_builtup', 'Industrial Built-up'), ('amenity', 'Amenity Plot'), ('mixed', 'Mixed Purpose'), ('all', 'All / General')], default='all', max_length=30)),
                ('rule_name', models.CharField(max_length=200)),
                ('min_age', models.IntegerField(blank=True, help_text='Age band lower bound (exclusive)', null=True)),
                ('max_age', models.IntegerField(blank=True, help_text='Age band upper bound (inclusive); blank = no limit', null=True)),
                ('adjustment_type', models.CharField(choices=[('reduction_pct', 'Percentage Reduction'), ('increase_pct', 'Percentage Increase'), ('factor_pct', 'Percentage Factor of another value'), ('set_open_plot', 'Set to Open-Plot Value'), ('note', 'Informational / Definition')], max_length=20)),
                ('adjustment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('version', models.ForeignKey(blank=True, help_text='Blank = applies to all versions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='TaxBuddyApp.propertyfmvrateversion')),
            ],
            options={
                'verbose_name': 'FMV Rule',
                'db_table': 'fmv_rules',
                'ordering': ['property_type', 'sort_order', 'rule_code'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFMVArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbr_no', models.IntegerField(blank=True, help_text='Serial no. in the FBR notification', null=True)),
                ('city', models.CharField(db_index=True, default='Karachi', max_length=60)),
                ('area_name', models.CharField(db_index=True, help_text='Exact FBR area description — do NOT normalise', max_length=300)),
                ('residential_open_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('residential_builtup_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commercial_open_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commercial_builtup_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('industrial_open_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('industrial_builtup_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_markers', models.JSONField(blank=True, default=dict, help_text="{'industrial_open_rate':'na'} for explicit N/A cells")),
                ('is_flagged', models.BooleanField(default=False, help_text='Source column mapping ambiguous — verify before relying on it')),
                ('is_dha', models.BooleanField(default=False, help_text='Area qualifies for the DHA Khayaban +15% rule (p)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='TaxBuddyApp.propertyfmvrateversion')),
            ],
            options={
                'verbose_name': 'FMV Area Rate',
                'db_table': 'fmv_areas',
                'ordering': ['version', 'area_name'],
                'indexes': [models.Index(fields=['version', 'area_name'], name='fmv_areas_version_a64fe8_idx'), models.Index(fields=['city'], name='fmv_areas_city_5e146c_idx')],
                'unique_together': {('version', 'area_name')},
            },
        ),
    ]
