# Generated by Django 5.2 on 2025-08-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0012_alter_taxbracket_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxbracket',
            name='surcharge',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
