# Generated by Django 5.2 on 2025-08-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0013_taxbracket_surcharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxbracket',
            name='surcharge',
        ),
    ]
