# Generated by Django 5.0.7 on 2025-08-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0015_propertytaxbracket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyTaxBracket',
            new_name='Business_AOP_Slab',
        ),
    ]
