# Generated by Django 5.2 on 2026-01-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0019_category_alter_option_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category', 'id']},
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='General', help_text='e.g. Basic Income Tax, Withholding Tax', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='section_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
