# Generated by Django 5.0.7 on 2026-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0020_alter_question_options_alter_question_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperTax4CRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField()),
                ('income_from', models.BigIntegerField()),
                ('income_to', models.BigIntegerField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
    ]
