# Generated by Django 5.0.7 on 2026-02-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxBuddyApp', '0021_supertax4crate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supertax4crate',
            name='income_to',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
